name: Test Runner (matrixed)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  matrixed:
    name: with Matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python:
        # 3.11.0a7 :: pyenv-action claims it isn't installed, despite pyenv seeming to install it without error
        - 3.10.4
        - 3.9.12
        - 3.8.13
        - 3.7.13
        - 3.6.15
        - 3.5.10
        # 3.5.3 and below :: require OpenSSL 1.0; won't build with anything more recent

        docutils:
        - 0.19.0
        - 0.18.1
        - 0.17.1
        - 0.16.0
        - 0.15.2
        - 0.14.0
        - 0.13.1
        - 0.12.0
        - 0.11.0
        - 0.10.0
        # 0.9.1 :: Not compatible with python >= 3.3 (https://sourceforge.net/p/docutils/bugs/196/)

        exclude:
        - {python: 3.6.15, docutils: 0.19.0}
        - {python: 3.5.10, docutils: 0.19.0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pyenv
      uses: "gabrielfalcao/pyenv-action@v10"
      with:
        default: ${{ matrix.python }}
        command: pip install -U pip

    - name: Setup docutils
      run: |
        pip install docutils==${{ matrix.docutils }}

    - name: Install package
      run: |
        pip install .

    - name: Execute tests
      run: |
        cd tests
        python -u alltests.py
